"""
Django settings for nettoyage_auxerre project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# Charger le fichier .env explicitement
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-+3(1h7coi)hpahn&u)&w+es4^1f*kq110n2fopqhxe1su)2_!$',
)

# En production, DEBUG doit être False.
_debug_env = os.environ.get('DJANGO_DEBUG', os.environ.get('DEBUG', 'False'))
DEBUG = str(_debug_env).strip().lower() in ('1', 'true', 'yes', 'on')

_allowed_hosts_env = os.environ.get('ALLOWED_HOSTS', '').strip()
if _allowed_hosts_env:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(',') if h.strip()]
elif DEBUG:
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = [
        'mycleaning.studio',
        'www.mycleaning.studio',
        'mycleaning-sites-4vyvg.ondigitalocean.app',
    ]
CSRF_TRUSTED_ORIGINS = [
    'https://mycleaning.studio',
    'https://www.mycleaning.studio',
    'https://mycleaning-site.onrender.com',
    'https://mycleaning-sites-4vyvg.ondigitalocean.app',
]
# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Doit être AVANT django.contrib.admin !
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'reservations',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'nettoyage_auxerre.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nettoyage_auxerre.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import dj_database_url
from urllib.parse import urlparse

# Base de données locale par défaut (SQLite)
# En production, on doit fournir une URL (ex: PostgreSQL) via variable d'environnement.
database_url = (
    os.environ.get('DATABASE_URL')
    or os.environ.get('DATABASE_URL')
    or ''
).strip()

if database_url and '://' in database_url and database_url != '://':
    DATABASES = {
        'default': dj_database_url.parse(database_url, conn_max_age=600)
    }
else:
    # Utiliser SQLite en développement local
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'reservations/static'),
# C'est ici qu'on dit à WhiteNoise où stocker les fichiers en ligne
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Cette ligne est magique : elle compresse les fichiers pour que le site soit plus rapide
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (Photos, uploads)
MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuration Gmail SMTP
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = 'contact@mycleaning.studio'

# Email admin pour les notifications
ADMIN_EMAIL = os.environ.get('ADMIN_EMAIL')

# HTTPS et sécurité des cookies
# En développement (DEBUG=True), on désactive la sécurité HTTPS
# En production (DEBUG=False), on force HTTPS
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SECURE_SSL_REDIRECT = not DEBUG

# === CONFIGURATION DU TABLEAU DE BORD (JAZZMIN) ===
JAZZMIN_SETTINGS = {
    # Titre de la fenêtre
    "site_title": "MyCleaning Admin",
    
    # Titre sur l'écran de connexion
    "site_header": "MyCleaning",
    
    # Texte sur le logo en haut à gauche
    "site_brand": "✨ MyCleaning Pro",
    
    # Message de bienvenue
    "welcome_sign": "Bienvenue dans l'espace gestion MyCleaning",
    
    # Copyright en bas
    "copyright": "MyCleaning Studio 2026",
    
    # Affichage du sidebar
    "show_sidebar": True,
    "navigation_expanded": True,
    
    # Cacher certaines choses qu'on ne veut pas voir
    "show_ui_builder": False,
}

JAZZMIN_UI_TWEAKS = {
    "theme": "litera",  # Un thème clair et moderne (très pro)
    "navbar": "navbar-white navbar-light",
    "sidebar": "sidebar-dark-primary",
}