# Generated by Django 5.2.13 on 2026-04-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeNettoyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('numero_telephone', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('type_prestation', models.CharField(choices=[('AIRBNB', 'AirBnb'), ('BUREAU', 'Bureau'), ('MAISON', 'Maison / Appartement')], max_length=20, verbose_name='Type de prestation')),
                ('surface', models.IntegerField(verbose_name='Surface (en m²)')),
                ('rue', models.CharField(max_length=255, verbose_name='Numéro et nom de rue')),
                ('code_postal', models.CharField(max_length=5, verbose_name='Code postal (5 chiffres)')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('nombre_chambres', models.IntegerField(default=0, verbose_name='Nombre de chambres')),
                ('nombre_salons', models.IntegerField(default=0, verbose_name='Nombre de salons')),
                ('nombre_bureaux', models.IntegerField(default=0, verbose_name='Nombre de bureaux')),
                ('nombre_toilettes', models.IntegerField(default=1, verbose_name='Nombre de toilettes/SdB')),
                ('materiel_sur_place', models.BooleanField(default=False, verbose_name='Matériel fourni sur place')),
                ('statut', models.CharField(choices=[('ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée')], default='ATTENTE', max_length=20)),
                ('commentaire_admin', models.TextField(blank=True, null=True, verbose_name='Message de Ramatoulaye')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
