# Generated by Django 5.2.13 on 2026-04-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandenettoyage',
            name='commentaire_admin',
            field=models.TextField(blank=True, null=True, verbose_name='Message au client (MyCleaning)'),
        ),
    ]
