# Generated by Django 5.2.13 on 2026-04-13 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_demandenettoyage_commentaire_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeAcceptee',
            fields=[
            ],
            options={
                'verbose_name': 'Demande Acceptée',
                'verbose_name_plural': '✅ Demandes Acceptées',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reservations.demandenettoyage',),
        ),
    ]
