# Generated by Django 5.2.13 on 2026-04-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_demandeacceptee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=100, verbose_name='Nom du client')),
                ('note', models.IntegerField(choices=[(5, '⭐⭐⭐⭐⭐ 5 stars'), (4, '⭐⭐⭐⭐ 4 stars'), (3, '⭐⭐⭐ 3 stars'), (2, '⭐⭐ 2 stars'), (1, '⭐ 1 star')], verbose_name='Note')),
                ('texte', models.TextField(verbose_name='Avis')),
                ('type_prestation', models.CharField(choices=[('AIRBNB', 'AirBnb'), ('BUREAU', 'Bureau'), ('MAISON', 'Maison / Appartement'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='Type de prestation')),
                ('publie', models.BooleanField(default=True, verbose_name='Publié')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='photos_nettoyage/', verbose_name='Image')),
                ('type_prestation', models.CharField(choices=[('AIRBNB', 'AirBnb'), ('BUREAU', 'Bureau'), ('MAISON', 'Maison / Appartement'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='Type de prestation')),
                ('affichee', models.BooleanField(default=True, verbose_name="Affichée sur l'accueil")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['-date_creation'],
            },
        ),
    ]
