# Generated by Django 5.2.13 on 2026-04-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_avis_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandenettoyage',
            name='details_prestation',
            field=models.TextField(blank=True, help_text='Décrivez précisément votre demande de nettoyage (zones prioritaires, type de nettoyage, etc.)', null=True, verbose_name='Détails de la prestation'),
        ),
    ]
