# Generated by Django 5.2.13 on 2026-04-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_demandenettoyage_details_prestation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='titre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titre'),
        ),
    ]
