# Generated by Django 5.2.13 on 2026-04-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_photo_description_alter_photo_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandenettoyage',
            name='date_souhaitee',
            field=models.DateField(blank=True, null=True, verbose_name="Date souhaitée pour l'intervention"),
        ),
    ]
