# Generated by Django 5.2.13 on 2026-04-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_demandenettoyage_date_souhaitee'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandenettoyage',
            name='prix_devis',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix du devis (€)'),
        ),
    ]
